### ISSUE TITLE
crypton-x509's test suite depends on x509

### ISSUE THREAD

**Issue by ysangkok** [kazu-yamamoto/crypton-certificate#10]
I think it would be better if the test suite depended on crypton-x509 instead of x509.

See:

https://github.com/kazu-yamamoto/crypton-certificate/blob/main/x509/crypton-x509.cabal#L57

This caused tests to get disabled in Stackage, see build-constraints.yaml.

**Comment by kazu-yamamoto** [comment]
I have released a new version which uses `crypton-x509` for testing.
